#!/bin/bash -e

TSV_FILE="rev.tsv"

buildDir() {
	echo "-- $1"

	if ! go test "$1" 2> /dev/null; then
		for subdir in `find "./src/$1" -mindepth 1 -maxdepth 1 -type 'd'`; do
			submod=`echo "$subdir" | sed 's#^\./src/##'`
			buildDir "$submod"
		done
	fi
}

PKGS=`awk '{ print $1; }' < "$TSV_FILE"`
for pkg in $PKGS; do
	buildDir "$pkg"
done
