#!/bin/bash -e

printHelp() {
	echo "------------------"
	echo "  Gopher Path     "
	echo "------------------"
	echo
	echo "Usage:"
	echo
	echo "  $0 [-dir DIR] [-color yes|no|auto] <commad>"
	echo
	exit 1
}

WDIR=`pwd`
CMD=""

while [[ $# > 0 ]]
do
	key="$1"
	shift
	case $key in
		-d|-dir|--dir)
			WDIR="$1"
			shift
		;;
		-c|-color|--color)
			COLOR="$1"
			shift
		;;
		-h|-help|--help)
			printHelp
		;;
		*)
			CMD="$key $@"
			break
		;;
	esac
done

if [[ "x$CMD" == "x" ]]; then
	printHelp
fi

cd "$WDIR"
export GOPATH=`pwd`

# Detect color
case $COLOR in
	yes)
		export GOPHERPATH_COLOR="yes"
	;;
	no)
		export GOPHERPATH_COLOR="no"
	;;
	*)
		# auto
		ncolors=$(tput colors)
		if [ -t 1 ] && test -n "$ncolors" && test $ncolors -ge 8; then
			export GOPHERPATH_COLOR="yes"
		else
			export GOPHERPATH_COLOR="no"
		fi
	;;
esac

bash -c "gopherpath-$CMD"
